FROM python:3.10.8-alpine

WORKDIR /usr/src/online_shop_django
ADD . /usr/src/online_shop_django

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

ENV HOME=/usr/src/online_shop_django

#RUN python manage.py makemigrations
#RUN python manage.py migrate
#RUN python manage.py collectstatic

RUN mkdir $HOME/static
#WORKDIR $HOME/static