version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - media_volume:/usr/src/online_shop_django/media
    ports:
      - '0.0.0.0:8000:8000'
    env_file:
      - ./.env.dev
volumes:
  media_volume:
