version: '3.8'

services:
  backend-master:
    build:
      context: .
      dockerfile: Dockerfile-prod
    image: porter/backend
    container_name: online_shop_django
    env_file:
      - ./.env.prod

  web:
    image: porter/backend
    depends_on:
      - backend-master
      - migration
    command: gunicorn online_shop_django.wsgi:application -c gunicorn.conf.py
    volumes:
      - static_volume:/usr/src/online_shop_django/static
      - media_volume:/usr/src/online_shop_django/media
    expose:
      - 8000

  migration:
    image: porter/backend
    command: python manage.py migrate --noinput
    volumes:
      - .:/usr/src/online_shop_django
  
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/online_shop_django/static
      - media_volume:/usr/src/online_shop_django/media
    ports:
      - '1337:90'
    depends_on:
      - web
volumes:
  static_volume:
  media_volume:
