version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn online_shop_django.wsgi:application -c gunicorn.conf.py
    volumes:
      - static_volume:/usr/src/online_shop_django/static
      - media_volume:/usr/src/online_shop_django/media
    expose:
      - 8000
    env_file:
      - ./.env.dev
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/online_shop_django/static
      - media_volume:/usr/src/online_shop_django/media
    ports:
      - '1337:90'
    depends_on:
      - web
volumes:
  static_volume:
  media_volume:
